### ISSUE TITLE
lmp_ftello is not exported

### ISSUE THREAD

**Issue by QuLogic** [iris-edu/libmseed#12]
The `seisan2mseed` package [uses `lmp_ftello`](https://github.com/iris-edu/seisan2mseed/blob/master/src/seisan2mseed.c#L296), but it is not exported from the shared library or DLL. This would be fine if you use the builtin copy, but for packaging we prefer to remove that and link with a common copy. Since that common copy doesn't export `lmp_ftello`, `seisan2mseed` cannot be built against it.

**Comment by chad-iris** [comment]
As of felease v1.8 seisan2mseed no longer relies on `lmp_ftello`.
