### ISSUE TITLE
Debian packaging and licensing issues

### ISSUE THREAD

**Issue by paride** [iris-edu/libmseed#13]
Hello @chad-iris,

I started working on the Debian packaging for libmseed, mostly because I'd like to have `mseed2sac` and `sac2mseed` packaged. I encountered a few licensing issue you may want to fix:

A portion of `genutils.c` comes with a peculiar license:

https://github.com/iris-edu/libmseed/blob/master/genutils.c#L1584

This license:
- Is probably non-free, as it requires a portion of code (the char array) to remain untouched. (I know this is borderline, but it's enough for the package to be rejected from Debian.)
- It is not compatible with the GPL, as it contains an additional advertising clause. See https://www.gnu.org/licenses/license-list.en.html#OriginalBSD and https://www.gnu.org/licenses/bsd.html for some background.  This means that the software is probably not distributable anyway.
- The fact that the file has multiple licenses makes downstream packaging difficult, but this is a secondary issue.

Will you consider replacing `pivotal_gmtime_r()` with an alternative with a better license? As an alternative, do you think it's feasible to reimplement the function and properly release it under the GPLv3?

Thank you!

**Comment by paride** [comment]
This is an implementation of POSIX `time.h` which solves the year 2038 bug on systems where time_t is only 32 bits:

https://github.com/evalEmpire/y2038

**Comment by chad-iris** [comment]
Hi @paride,

Yes, I would like to replace "pivotal" piece.  Thanks for the alternative, I'll give it a look!

**Comment by chad-iris** [comment]
Closing as the conversation has moved to PR #14.

**Comment by vvug** [comment]
@duperray Was this finally solved? I'm looking forward to see libmseed in Debian!

Also I'd like to see SAC, but unfortunately the its license is non-free.

**Comment by duperray** [comment]
well, I'm waiting my sponsor to upload it to unstable, I will keep you informed.

I use obspy as a dropin replacement for SAC, for which libmseed is a dependency.
an attempt was done to package obspy in debian.
but first things first :)
