### ISSUE TITLE
lmplatform.h

### ISSUE THREAD

**Issue by NimaDolatabadi** [iris-edu/libmseed#16]
using `make gcc` runs with error: make: *** `No rule to make target gcc.  Stop.`
but i need **lmplatform.h** for my files but simply using `make` does not make it.
so how can I fix this problem?
regards

**Comment by chad-iris** [comment]
lmplatform.h is not a generated file.  It was removed from the repository with the 2.19 release with this note:
* Incorporate lmplatform.h details into libmseed.h for improved usage.  All that is needed is the static/shared/dynamic library and libmseed.h.

If you think you still need it for some reason please reopen.

Also, there is no `gcc` make/build target and there likely never will be again, that was an a shortcut for early development that was originally removed.
