### ISSUE TITLE
#include unistd.h on GNU/Hurd and kFreeBSD

### ISSUE THREAD

**Issue by paride** [iris-edu/libmseed#26]
In `libmseed.h`, `unistd.h` needs to be included on GNU/Hurd systems (`__GNU__`) and GNU/kFreeBSD systems (`__FreeBSD_kernel__ && __GLIBC__`). Relevant issue:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890571

**Comment by chad-iris** [comment]
Fixed in d32d8326cbf2f8adf4585aeb866a4041ad998234.

`unistd.h` is included for everything not Windows.
