### ISSUE TITLE
libmseed.so.2.18 in libmseed-2.19

### ISSUE THREAD

**Issue by crish4cks** [iris-edu/libmseed#3]
Hi,
I noticed the minor version number for the release 2.19 has been left to 18. Is that intentional?
Thank you in advance for your time.

Cristiano.

**Comment by chad-iris** [comment]
No, that was an oversight.  I'll tag a new release soon, after I check into possibilities to avoid this in the future.  Somehow I need to propagate the version from a single place.

Thanks for reporting!

**Comment by QuLogic** [comment]
I don't see any 2.19 release?

**Comment by chad-iris** [comment]
The release tag has been removed while a new one is prepared.

**Comment by chad-iris** [comment]
Fixed in b45744cb5a284664be59f17447f5a737d730a2be
