### ISSUE TITLE
On 8bit Compression in Steim 2 Compression

### ISSUE THREAD

**Issue by HuangXinf** [iris-edu/libmseed#36]
hello
i'm reference your code to pack and unpack the miniseed with steim2, but i found some confuse about the page146 figure 14 steim 2 compression data format on in SEED Format Version 2.4 .
int the figure,30bit,15bit,10bit,8bit,6bit,5bit,4bit all show the d0  to d.n(MSB to LSB), but in your code, the 8bit is difference(in little-endian), the it is dn to d0.

```
     /* 4 x 8-bit differences */
      else if (diffcount >= 4 &&
               bitwidth[0] <= 8 && bitwidth[1] <= 8 &&
               bitwidth[2] <= 8 && bitwidth[3] <= 8)
      {
        if (encodedebug)
          ms_log (1, "  W%02d: 01=4x8b  %d  %d  %d  %d\n",
                  widx, diffs[0], diffs[1], diffs[2], diffs[3]);

        word = (union dword *)&frameptr[widx];

        word->d8[0] = diffs[0];
        word->d8[1] = diffs[1];
        word->d8[2] = diffs[2];
        word->d8[3] = diffs[3];

        /* 2-bit nibble is 0b01, only need to set 2nd bit */
        frameptr[0] |= 0x1ul << (30 - 2 * widx);

        packedsamples = 4;
      }
```
  In this part of the code, diffs [0] is the lowest byte in U32 if it is in small-end format. Other formats store diffs [0] from the high to the low of U32. Normally, d0, d1, d2 are from the high to the low of U32 or from the low to the high?
  The following figure shows debug data for this source code compression.
![image](https://user-images.githubusercontent.com/48211131/53807173-da79de00-3f89-11e9-8522-2483ac76685f.png)
 This is a screenshot of the IRIS SEED Format Version 2.4 August, 2012。

![image](https://user-images.githubusercontent.com/48211131/53807482-a226cf80-3f8a-11e9-9f4b-a7b4cd46500f.png)

**Comment by chad-iris** [comment]
Hello @HuangXinf.

I believe you are discussing little-endian Steim2 compressed data.  Please note that Steim2 is only defined in SEED as big-endian.  Little-endian Steim2 is not officially allowed in the standard.  The support for little-endian in libmseed matches that contained in the qlib2 (http://www.ncedc.org/ftp/pub/quanterra/ucb/) library.  Essentially this means little-endian Steim2 is only defined by software. 

If I have misunderstood your point please let me know.

**Comment by HuangXinf** [comment]
Okay, I see. Thank you.
