### ISSUE TITLE
Damaged mseed file?

### ISSUE THREAD

**Issue by admoure** [iris-edu/libmseed#46]
_lm_pack_ example generates a mseed file that apparently is correct but it can not be opened with other software as python or matlab.

**Comment by chad-iris** [comment]
Hi @admoure, as noted in the [release notes ](https://github.com/iris-edu/libmseed/releases) for the new major version 3 of the library, the default output is a _new_ data format.

If you need to create miniSEED version 2, which is currently in widespread use, I suggest sticking with version 2.x releases of the library for now.
