### ISSUE TITLE
make install fails due to missing files in doc/

### ISSUE THREAD

**Issue by senshu** [iris-edu/libmseed#47]
I have built libmseed v3.0.2 successfully using `make shared`.

`make install` fails with the following message:

```
cp: cannot stat 'doc/libmseed-UsersGuide': No such file or directory
```

In fact `doc/libmseed-UsersGuide` is missing from the source tree and there is no rule in the Makefile to create it.

The `install` target also contains this command, which will fail because the files `doc/ms*.3` do not exist:

```
@cp -a doc/ms*.3 $(DESTDIR)$(MAN3DIR)/
```

**Comment by chad-iris** [comment]
Thanks @senshu!  Fixed in ec7a205f10ab6a39fb25a2ac4d3c80f9a7b9fb49
