### ISSUE TITLE
Allow month-day date-times in selections

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/libmseed#48]
It would be very nice if the selection file format supported "Year-Month-Day" dates in addition to "Year-DayOfYear" form.  The challenge is made more complex by a) the date-times are allowed to be short, specifying only a date, only an hour, etc. and b) the fields in the file can be in different columns depending on file format.

Allowing both date formats might require more strictness in the forms.  Review is required to determine if this can be detected unambiguously.

**Comment by dsentinel** [comment]
...along these lines I was caught up by a short endtime not including the entirety e.g.
endtime year 2018
I would expect to include 2018:365:24:60:60
or 2019:00... 
Perhaps I'm alone on this, and I can just add 1 to the year

**Comment by chad-iris** [comment]
As of v3.0.6 any time formats recognized by ms_timestr2nstime() may now be used in selection files.

@dsentinel, yeah that's a tricky problem.  Adding context ("start" versus "end") when converting short times is non-trivial and can make usage really confusing.  But it's a common problem across web service interfaces, library APIs, etc.

I've been thinking along the lines of supporting time designations that are non-inclusive.  For example, a user requests and end time of `<2019` (or `(2019` for traditional interval syntax) which would mean anything before the year 2019 but not including 2019-1-1T0:0:0.
