### ISSUE TITLE
watcom error

### ISSUE THREAD

**Issue by microxpgg** [iris-edu/libmseed#55]
When i run "nmake -f makefile.win" under windows 10 using watcom,got the following errors:

extraheaders.c(392): Error! E1063: Missing operand
extraheaders.c(392): Error! E1009: Expecting ')' but found '{'
extraheaders.c(392): Note! N2002: 'memcmp' defined in: F:\WATCOM\H\string.h(145)
extraheaders.c(392): Error! E1151: Parameter count does not agree with previous definition
extraheaders.c(392): Error! E1009: Expecting ')' but found '0'
extraheaders.c(392): Error! E1063: Missing operand
extraheaders.c(392): Warning! W111: Meaningless use of an expression
extraheaders.c(392): Warning! W111: Meaningless use of an expression
extraheaders.c(392): Error! E1009: Expecting ';' but found ','
extraheaders.c(392): Warning! W111: Meaningless use of an expression
extraheaders.c(392): Warning! W111: Meaningless use of an expression
extraheaders.c(392): Warning! W111: Meaningless use of an expression
extraheaders.c(392): Warning! W111: Meaningless use of an expression
extraheaders.c(392): Error! E1009: Expecting ';' but found '}'
extraheaders.c(392): Warning! W107: Missing return value for function 'mseh_add_event_detection'
extraheaders.c(392): Error! E1061: Expecting data or function declaration, but found ','
extraheaders.c(392): Error! E1026: Invalid declarator
extraheaders.c(392): Error! E1009: Expecting ';' but found '6'
extraheaders.c(392): Error! E1061: Expecting data or function declaration, but found 'constant'
extraheaders.c(392): Error! E1026: Invalid declarator
extraheaders.c(392): Error! E1009: Expecting ';' but found ')'
extraheaders.c(392): Error! E1061: Expecting data or function declaration, but found ')'
extraheaders.c(392): Error! E1026: Invalid declarator
extraheaders.c(392): Error! E1009: Expecting ';' but found ')'
extraheaders.c(392): Error! E1061: Expecting data or function declaration, but found ')'
extraheaders.c(393): Error! E1026: Invalid declarator
extraheaders.c(393): Error! E1009: Expecting ';' but found '{'
extraheaders.c(393): Error! E1061: Expecting data or function declaration, but found '{'
extraheaders.c(394): Error! E1147: Too many errors: compilation aborted
Error(E42): Last command making (extraheaders.obj) returned a bad status
Error(E02): Make execution terminated

And everything is fine when i make the libmseed 2.x

**Comment by chad-iris** [comment]
Hello @microxpgg, the Watcom compiler is no longer supported.  The last stable release was many years ago.  But I see there is a revival project so perhaps it's coming back.

There are free alternatives that are know to work:
MS Visual Studio (Community): https://visualstudio.microsoft.com/downloads/
MinGW: http://www.mingw.org/

The project should also compile fine in Cygwin: https://www.cygwin.com/
