### ISSUE TITLE
Please keep namespaces separate

### ISSUE THREAD

**Issue by jsaul** [iris-edu/libmseed#58]
Currently the version 3 of libmseed implements a new data format also known under the name "next generation format" or "NGF" [1], following discussions within FDSN Working Group 2, and more recently also under the name "extended miniSEED" or "xSEED" by IRIS [2]. While "NGF" was chosen as a temporary name to avoid confusion with miniSEED, "xSEED" seems like a brilliant name for the new format, as it nicely symbolizes an extension of the SEED family of data formats.

Naming the new data format (NGF, xSEED, miniSEED3, ...) consistently as "xSEED" offers several advantages:

* Ensure coherency in the naming of the various "SEED" family members.

* Avoid the ambiguous use of the name "mseed" or "miniSEED" for two very different formats and supporting libraries.

* Have two separate libraries libmseed and libxseed.

The current use of the name "libmseed" for a library supporting current miniSEED in version 2 and xSEED/NGF in version 3 is not only confusing but also problematic from a technical point of view. Continuation of the version 2 currently takes place somewhat hidden within a branch of libmseed. Whereas the main branch (version 3) libmseed is not compatible with most software that once adopted libmseed in good faith. Using the same name for two different libraries will also  make linking against both at least cumbersome if not impossible, whereas separate libmseed and libxseed would allow to more cleanly distinguish between the two libraries and link against both wherever needed.

[1] https://github.com/FDSN/miniSEED3-TechnicalEvaluation/issues/26
[2] https://iris-edu.github.io/xseed-specification

**Comment by chad-iris** [comment]
The FDSN has not decided on what the name of the new format shall be, most of this is moot until that is decided.

Regarding different versions of the library for different formats, it may help to understand that:

* version 3 of the library supports both formats, it is a superset of version 2 in functionality.

* given that, the use cases for needing both versions of the library are vanishingly narrow.  Porting to version 3 API is required, but after that, version 2 should not be needed by an application.

* the two formats are quite similar in fit, form, function and will likely be used side by side for a long time.  Supporting them seamlessly is necessary and with the branding already established is very valuable.  The vast majority of users will not care which is used, just that it works.  From this perspective, splitting the name of the library is not only unnecessary but is probably more confusing and more work than it's worth.

> Continuation of the version 2 currently takes place somewhat hidden within a branch of libmseed. 

It is far from hidden, releases will remain, along with future versions, on the releases page: https://github.com/iris-edu/libmseed/releases.
