### ISSUE TITLE
doc: please include a local copy of the IRIS logo

### ISSUE THREAD

**Issue by paride** [iris-edu/libmseed#63]
In order to make the generated HTML documentation fully functional offline please include a local copy of the IRIS logo instead of fetching it at runtime, here:

https://github.com/iris-edu/libmseed/blob/master/doc/footer.html#L4

I think that's the only line to change. I understand the documentation is meant to be pushed to GitHub pages, however a copy of the generated HTML files is going to be included as a Debian/Ubuntu package for offline reference. Think of the people doing field work in Antarctica :-)

**Comment by chad-earthscope** [comment]
Done in 497dff7343cdcf42e40b24781761d53fdc0ac991
