### ISSUE TITLE
Stray LGPL licensing line 

### ISSUE THREAD

**Issue by paride** [iris-edu/libmseed#64]
I think this line:

https://github.com/iris-edu/libmseed/blob/master/libmseed.h#L22

should go now that libmseed is Apache licensed.

**Comment by yensoon2** [comment]
Good afternoon @chad-iris,

I believe that this issue [has already been fixed](https://github.com/iris-edu/libmseed/commit/4b3e4afd767c42377f34c7f0c7ffe420070f6df5) in [libmseed v3.0.8](https://github.com/iris-edu/libmseed/tree/v3.0.8), so this issue can now be closed.

Thank you very much for writing [libmseed](https://github.com/iris-edu/libmseed)!
