### ISSUE TITLE
suggestion: always set pubversion to 0 when calling ms3_readtracelist_timewin()

### ISSUE THREAD

**Issue by Cuda-Chen** [iris-edu/libmseed#65]
Hi Chad,

Currently I am using your awesome work.
When I try to call `ms3_readtracelist_timewin()` I always receive an error about 'No miniSEED data detected'. 
However, when I use `ms3_readselectionsfile()` to read the selection then call `ms3_readtracelist_selection()` to select the data within the time window, this problem disappears.
After some investigation, I find there is a difference when creating `MS3Selections` struct and filling its data between `ms3_readtracelist_timewin()` and `ms3_readselectionsfile()`:
1. In `ms3_readtracelist_timewin()`, the function **DOES NOT** set the value of `pubversion`.
```c=604
  selection.sidpattern[0] = '*';
  selection.sidpattern[1] = '\0';
  selection.timewindows   = &selecttime;
  selection.next          = NULL;
```

2. Whereas in `ms3_readselectionsfile()` the function ***DOES*** set the value of `pubversion` to zero if there is no pubversion specify in the input file.
```
    /* Test for "SourceID  [Starttime  [Endtime  [Pubversion]]]" */
    if (fieldidx == 1 ||
        (fieldidx == 2 && isstart2) ||
        (fieldidx == 3 && isstart2 && isend3) ||
        (fieldidx == 4 && isstart2 && isend3 && ms_isinteger(fields[3])))
    {
      /* Convert publication version to integer */
      pubversion = 0;
      if (fields[3]) /* It Pubversion fields exists) */
      {
       ...
      }
```

IMHO, I think we can set the `pubversion` to zero in `ms3_readtracelist_timewin()`.
If you think this is a great idea, I will send a PR at once :)

**Comment by chad-iris** [comment]
Thanks for looking into this @Cuda-Chen.  From your description there appears to be an error/inconsistency.  Sure, if the PR is easy please send it in.  Otherwise I'll look into this in the next month.

**Comment by Cuda-Chen** [comment]
Hi Chad,
I have sent the PR to solve this problem.
I also create an example program, which is adapted from `lm_read_selection.c`, to show the usage of `lm_read_timewin()`.
Feel free to edit the PR and example program if needed.
