### ISSUE TITLE
msrepack.c example, unresolved symbol

### ISSUE THREAD

**Issue by duperray** [iris-edu/libmseed#7]
Hi Chad,
I get an unresolved symbol when building msrepack.c in example folder:
msrepack.o: In function `main': 
msrepack.c:(.text+0x16d): undefined reference to `unpackencodingformat'

in libmseed.h, I see you declare an extern int unpackencodingformat;
defined in unpack.c
Perhaps I was a bit too restrictive with the exported external symbols?

regards,

Pierre

**Comment by chad-iris** [comment]
Noted, I'll get that symbol added.

**Comment by chad-iris** [comment]
Fixed in 090b05c398865445f0841e61a8f95ca675561f48
