### ISSUE TITLE
Valgrind Uninitialized Error

### ISSUE THREAD

**Issue by bakerb845** [iris-edu/libmseed#70]
Tracking through valgrind I get an uninitialized variable issue.  The order of calls looks like: 

(1) ms3_readtracelist calls 
(2) ms3_readtracelist_selection where line 675 in fileutils.c has int64_t fpos which calls 
(3) ms3_readmsr_selection then at line 304 I get the uninitialized error which seems sensible.

Setting line 675 to int64_t fpos = 0; 

This seems a little suspect since fpos might not be appropriate given it may require some consistency with the open file.

**Comment by chad-iris** [comment]
Thanks.  Is this on current `master` branch or some other tagged release?

**Comment by bakerb845** [comment]
Hey Chad, this is on the current master.  I think the issue may have existed for at least a few months on libmseed v3.  Unfortunately, I was tracking a problem with my codes, valgrind complained, so I just pulled the latest from the master hoping the problem would magically disappear.  I didn't note my previous libmseed3 version.  Sorry!

**Comment by chad-iris** [comment]
No worries.  Thanks for the report.  Valgrind is awesome for this kind of thing, keeps C honest until we wholesale move to Rust...

**Comment by dsentinel** [comment]
Related. Apologies for a terrible bug report, this is from memory.
When:
 `ms3_readtracelist(` without `UNPACKDATA` and then again with `UNPACKDATA`
I think I saw `datasamples` `alloc`'d twice, leaving a dangling pointer from the first call.... or maybe some other memory bug that valgrind should easily catch.
I meant to make a proper case report, and PR, but alas, time.

**Comment by anowacki** [comment]
I'm pretty certain that the lack of initialisation of `fpos` on line 675 of `fileutils.c` has been causing errors for me, and that initialising it to 0 fixes those issues.

For background, I'm wrapping libmseed in a Julia package, and I have several tests calling `ms3_readtracelist` a total of I guess ~100 times.  My tests were failing on certain machine and architecture combinations, with files not being read properly.  (See e.g. https://github.com/anowacki/LibMseed.jl/runs/5971465915?check_suite_focus=true for error messages logged by libmseed amongst all the Julia stuff.)  In short, calls to `ms3_readtracelist` for data which had just been written by `msr3_writemseed` and existing test data were returning a `MS_NOTSEED` error, even though the files were valid miniSEED on disk, and other OS-architecture combinations were working.

Initialising `fpos` to 0 as suggested by @bakerb845 fixes these problems for me (e.g., https://github.com/anowacki/LibMseed.jl/runs/5981051328?check_suite_focus=true), so I wonder if you might want to include this change in a future version of libmseed soon?  I have submitted a PR to this effect (#80), but please do feel free to close that and deal with this as you see fit.
