### ISSUE TITLE
Re-license the libmseed 2.x branch under Apache License v2.0, then, release the next version of libmseed v2.x straight after

### ISSUE THREAD

**Issue by yensoon2** [iris-edu/libmseed#71]
[The libmseed 2.x branch](https://github.com/iris-edu/libmseed/tree/2.x) is still (as of 4 June 2021) licensed under the LGPL v3.0.

Most users of [libmseed](https://github.com/iris-edu/libmseed) are still on version 2.x.  Some of them strongly prefer the Apache License v2.0 to the LGPL v3.0.

Can you please **re-license** [the libmseed 2.x branch](https://github.com/iris-edu/libmseed/tree/2.x) under the Apache License v2.0, then, can you please release the next version of [libmseed](https://github.com/iris-edu/libmseed) v2.x straight after?

Thank you very much for your efforts!

**Comment by chad-iris** [comment]
I have no plans to relicense libmseed 2.x.

The next major version of the library, 3.x, will be licensed as Apache 2.
