### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by anowacki** [iris-edu/libmseed#81]
I apologise for the gumption in my making this suggestion, but I wonder given that `develop` now has a couple of bug fixes that `v3.0.9` doesn't (i.e., #65 and #70 plus the `crc32c` warning issue), whether it might be nice to tag a `v3.0.10`?

Of course you will have your own processes and timelines which I understand, but it will save us carrying a patch in https://github.com/JuliaBinaryWrappers/libmseed_jll.jl and also have `libmseed` cross compiled and working for [all these targets](https://github.com/JuliaBinaryWrappers/libmseed_jll.jl#platforms).

**Comment by anowacki** [comment]
Thanks, Chad!

**Comment by chad-iris** [comment]
You're welcome and it was time.

*NOTE* that this version of the library remains **PRE_RELEASE** as the version "3" of data format that it supports is not yet a standard.  Two things to keep in mind:
1) the v3 library API remains subject to change
2) the v3 format should not be used at all except for testing

The good news is that review of the v3 format is under review.

I also took the opportunity to rename the `master` branch to `main`.
